sections:
  - title: Major changes
    labels:
      - "release/super-feature"
  - title: Complete changelog
    labels:
      - "bug"
      - "enhancement"
      - "dependencies"
template: |
  Add Next.js helm chart template as dependency to Chart.yaml:
  ```yaml
    dependencies:
      - name: helm-nextjs-app
        alias: app
        version: "{{ .Version }}"
        repository: oci://ghcr.io/qnowak/charts
  ```

  {{ range $section := .Sections }}{{ if $section.Items }}### {{ $section.GetTitle }}{{ range $item := $section.Items }}
  * [#{{ $item.GetID }}]({{ $item.GetURL }}) - {{ $item.GetTitle }}{{ end }}{{ end }}
  {{ end }}
