name: Build Pull Request
on:
  pull_request:
    branches:
      - "main"
      - "fix/[0-9]+.[0-9]+.x"

jobs:
  helm:
    name: helm build and push
    runs-on: ubuntu-latest
    env:
      SAMO_HELM_ABSOLUTE_DIR: true
      SAMO_HELM_DIR: .
      SAMO_HELM_SOURCE_DIR: .
      SAMO_HELM_SOURCE_COPY: false
      SAMO_HELM_REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts
      SAMO_DOCKER_REGISTRY: ghcr.io
      SAMO_DOCKER_RELEASE_REGISTRY: ghcr.io
      SAMO_CONVENTIONAL_COMMITS: 'true'
      SAMO_HELM_CHART_TEMPLATE_LIST: version={{ .Version }},appVersion={{ .Version }},name={{ .Name }}
      SAMO_HELM_VALUES_TEMPLATE_LIST: app.image.registry=ghcr.io,app.image.tag={{ .Version }},app.image.repository=${{ github.repository_owner }}/{{ .Name }}
      SAMO_HELM_ADD_REPO_DEPS: false
      artifact: ""
      push: false
    steps:
      - uses: lorislab/install-samo-action@v2
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.SAMO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        if: ${{ env.artifact != '' }}
        with:
          name: ${{ env.artifact }}
          path: target
      - name: helm build
        run: samo project helm build -v debug
      - name: helm push
        if: ${{ env.push }}
        run: samo project helm push -v debug
