name: Build
on:
  push:
    branches:
      - "main"
      - "fix/[0-9]+.[0-9]+.x"
    tags:
      - "v*"

jobs:
  helm:
    name: helm build and push
    runs-on: ubuntu-latest
    env:
      SAMO_HELM_ABSOLUTE_DIR: true
      SAMO_HELM_DIR: .
      SAMO_HELM_SOURCE_DIR: .
      SAMO_HELM_SOURCE_COPY: false
      SAMO_HELM_REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts
      SAMO_DOCKER_REGISTRY: ghcr.io
      SAMO_DOCKER_RELEASE_REGISTRY: ghcr.io
      SAMO_CONVENTIONAL_COMMITS: 'true'

      SAMO_HELM_ADD_REPO_DEPS: false
      artifact: ""
      push: true
    steps:
      - uses: lorislab/install-samo-action@v2
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set VERSION from git tag (if present)
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.SAMO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CI_PAT }}
      - uses: actions/download-artifact@v4
        if: ${{ env.artifact != '' }}
        with:
          name: ${{ env.artifact }}
          path: target
      - name: helm build
        run: |
          VERSION="${VERSION:-$(yq '.version' Chart.yaml)}"
          export SAMO_HELM_CHART_TEMPLATE_LIST="version=${VERSION},appVersion=${VERSION},name=$(yq '.name' Chart.yaml)"
          export SAMO_HELM_VALUES_TEMPLATE_LIST="app.image.registry=ghcr.io,app.image.tag=${VERSION},app.image.repository=${{ github.repository_owner }}/$(yq '.name' Chart.yaml)"
          samo project helm build -v debug
      - name: helm push
        if: ${{ env.push }}
        run: samo project helm push -v debug
